### ISSUE TITLE
https://chat.opencontainers.org/ is down (NXDOMAIN)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/.github#39]
https://github.com/opencontainers/.github/blob/cb000d2b47bfbc9de1ec26c6001ecfa3fb23e73a/README.md#slack

> Gain access to OCI Slack here: https://chat.opencontainers.org/

The link is down (NXDOMAIN)

**Comment by tianon** [comment]
It doesn't fix the problem with chat.containers.org (something I can't help with), but if someone needs it, https://join.slack.com/t/opencontainers/shared_invite/zt-vzxfzkkl-CbsYY9zwMhSTkXlvvhmBVA should provide a working OCI Slack invite in the interim :smile:

**Comment by sudo-bmitch** [comment]
@caniszczyk @amye PTAL

**Comment by amye** [comment]
I think what happened is that the invite link expired, https://join.slack.com/t/opencontainers/signup is what I'm resetting it to.

**Comment by samuelkarp** [comment]
It looks like `chat.opencontainers.org` is currently a CNAME to `https://join.slack.com/t/opencontainers/signup`, but that's not valid as `https://join.slack.com/t/opencontainers/signup` is a URL rather than a DNS name.  `chat.opencontainers.org` would need to have an A record to some HTTP(S) server that can then issue a 3xx redirect to `https://join.slack.com/t/opencontainers/signup`.

**Comment by amye** [comment]
Well that explains that. I'll fix it shortly.

**Comment by nate-double-u** [comment]
I think this may sort it: https://github.com/opencontainers/opencontainers.org/pull/128

If not, there is another way using a _redirects file,  but it's a bit more complicated to set up.

**Comment by amye** [comment]
So the redirects file is failing, and I'm reopening this. All the redirects are failing now. :D

**Comment by TBBle** [comment]
https://opencontainers.org/community/overview/#chat links to https://communityinviter.com/apps/opencontainers/join-the-oci-community now, is that a temporary workaround? Or since the DNS entry for chat.opencontainers.org appears to be NXDOMAIN again, should this README (which is the first one I found when trying to local the Slack address) point to either that inviter, or just https://opencontainers.org/community/overview/#chat?
